name: Build pipeline

on:
  pull_request:
    branches: 
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   # excludes master

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps: 
      - name: Checkuot last version
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies 
        run: npm install --no-audit --no-fund --no-optinal

      - name: Remove previous dist dir for secutiry
        run: rm -r dist

      - name: Build proyect
        run: npm run build
        
      - name: Commit new dist dir
        run: |
          git config --global user.email 'github-actions@noreply.github.com'
          git config --global user.name 'GitHub-Actions'
          git add 'dist'
          git commit -am 'New dist folder made by GitHub-Actions'
          git push

